import ContactSection from "@/components/ContactUs/ContactUs";
import {
  Box,
  CardContent,
  Container,
  Grid,
  Paper,
  Typography,
} from "@mui/material";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <>
      <Box
        sx={{
          width: "100%",
          height: "400px",
          backgroundImage: "url(/banner2.avif)",
          backgroundSize: "cover",
          backgroundPosition: "center",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: "#fff",
          marginBottom: "2rem",
        }}
      >
        <Typography variant="h4" component="div">
          Home &gt;{" "}
          <Typography
            component="span"
            variant="h4"
            sx={{ color: "primary.main", fontFamily: "Arial, sans-serif" }}
          >
            About
          </Typography>
        </Typography>
      </Box>

      <Container maxWidth="lg" style={{ marginTop: "2rem" }}>
        <Typography
          sx={{
            fontFamily: "fantasy",
            textDecoration: "underline",
          }}
          component="h6"
          color={"primary.main"}
          variant="h4"
        >
          Contact Us
        </Typography>

        <Typography
          color={"primary.main"}
          sx={{
            fontSize: "2rem",
            fontWeight: "bold",
            padding: "4rem",
            fontFamily: "-moz-initial",
          }}
        >
          Thank you for your kind trust in explore-buddy! With 20 years of
          experience, our travel expert team will contact you soonest for the
          best trips and advice.
        </Typography>

        <ContactSection />
        <Grid
          container
          spacing={4}
          style={{ marginBottom: "2rem", marginTop: "2rem" }}
        >
          {[
            {
              city: "San Francisco",
              address: "1095 Howard Street, San Francisco, USA",
              phone: "+(123) 456-789-0123",
              email: "support@templaza.com",
            },
            {
              city: "New York",
              address: "3497 Watson Street Camden, NJ 08102",
              phone: "+(123) 456-760-9090",
              email: "info@templaza.com",
            },
            {
              city: "Paris",
              address: "1000 Effel Orlando Street, OL 445",
              phone: "+(123) 777-802-2190",
              email: "info@templaza.com",
            },
            {
              city: "Berlin",
              address: "3497 Edward Street, NB 4390",
              phone: "+(123) 870-510-0225",
              email: "info@templaza.com",
            },
          ].map((location, index) => (
            <Grid item xs={12} sm={6} key={index}>
              <Paper
                elevation={0}
                sx={{
                  transition: "border 0.3s ease-in-out",
                  "&:hover": {
                    border: "2px solid",
                    borderColor: "primary.main",
                  },
                }}
              >
                <CardContent>
                  <Typography
                    variant="h3"
                    component="h4"
                    style={{
                      fontFamily: "Arial, sans-serif",
                      marginBottom: "0.5rem",
                    }}
                  >
                    {location.city}
                  </Typography>
                  <Typography
                    variant="h6"
                    component="h5"
                    style={{
                      fontFamily: "Arial, sans-serif",
                      marginBottom: "0.5rem",
                    }}
                  >
                    {location.address}
                  </Typography>
                  <Typography
                    variant="body1"
                    style={{
                      fontFamily: "Arial, sans-serif",
                      marginBottom: "0.5rem",
                    }}
                  >
                    {location.phone}
                  </Typography>
                  <Typography
                    variant="h6"
                    component="h6"
                    style={{
                      fontFamily: "Arial, sans-serif",
                      marginBottom: "0.5rem",
                      color: "blue",
                    }}
                  >
                    {location.email}
                  </Typography>
                </CardContent>
              </Paper>
            </Grid>
          ))}
        </Grid>
      </Container>
    </>
  );
};

export default Contact;
